In [2]:
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import sys

PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "processed" / "tumorgrowth-processed.csv"
EXPORT_PATH = PROJECT_ROOT / "figures"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.models.improved_model import simulate_tumor
from src.models.fit_improved_model import fit_model, truncate_dataset

In [3]:
data = pd.read_csv(DATA_PATH)

data.head()

     Grp  Group   ID  Day   Size  Baseline       RTV
0  1.CTR      1  101    0   41.8      41.8  1.000000
1  1.CTR      1  101    3   85.0      41.8  2.033493
2  1.CTR      1  101    4  114.0      41.8  2.727273
3  1.CTR      1  101    5  162.3      41.8  3.882775
4  1.CTR      1  101    6  178.3      41.8  4.265550

In [4]:
%%time
seed = 23 ; maxiter = 10 ; popsize = 5

mouse_results, group_results = fit_model(data, seed, maxiter, popsize, 15)

group_results.head()

CPU times: total: 3min 30s
Wall time: 3min 51s

    ID  Group      r_id     eta_i
0  101      1  0.294472  0.004058
1  102      1  0.209422 -0.080992
2  103      1  0.319185  0.028771
3  104      1  0.244607 -0.045806
4  105      1  0.283735 -0.006678

In [5]:
mouse_results.head()

   Group   bar_r_s            K        al  sigma_r  Global_Loss
0      1  0.290414  7467.980254  0.000000      0.3     0.079517
1      2  0.290414  7467.980254  0.102278      0.3     0.079517
2      3  0.290414  7467.980254  0.034319      0.3     0.079517
3      4  0.290414  7467.980254  0.084812      0.3     0.079517